name: 'RST Substitution'
description: 'Replace substitutions in reStructuredText file'
author: 'junghoon-vans'
inputs:
  input-file:
    description: 'Input file path to read contents'
    required: false
  output-file:
    description: 'Output file path to write contents'
    required: false
  substitutions:
    description: 'Multiline strings for key-value pair of substitutions'
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python -m pip install varst
      shell: bash
    - run: |
        cmd="varst"

        if [ -n "${{ inputs.input-file }}" ]; then
          cmd+=" -i ${{ inputs.input-file }}"
        fi

        if [ -n "${{ inputs.output-file }}" ]; then
          cmd+=" -o ${{ inputs.output-file }}"
        fi

        eval "${cmd} ${{ inputs.substitutions }}"
      shell: bash
